branches:
  only: 
    - master
language: csharp
solution: sdk/DocuSign.eSign.sln
mono: none
sudo: required
dist: trusty
dotnet: 2.1.2

install:
  - dotnet restore ./sdk/src/DocuSign.eSign/DocuSign.eSign.csproj

script:
  - dotnet build --framework netstandard2.0 ./sdk/src/DocuSign.eSign/DocuSign.eSign.csproj